[package]
name = "kalman_filters_in_rust"
version = "0.1.0"
edition = "2021"

[dependencies]
nalgebra = {version = "0.33.0", default-features = false} # linear algebra library
libm = {version = "0.2.11"} # math lib for embedded
approx = {version = "0.5.1"} # approx test for floats
